name: Lint and Format

on: 
  pull_request:
    branches: main
  push:
    branches: main
concurrency:
# see here for information : https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
  group: ci - ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: github action debug
        run: |
          echo "ci - ${{ github.event.pull_request.number || github.ref }}"
          sleep 30
      
      - uses: actions/setup-python@v7
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
        
      - name : Code format using Black
        uses: psf/black@stable
        with:
          options: "--check --diff"

      - name : Code Analysis using Pylint
        run: |
          pylint $(git ls-files '*.py')



