name: Lint, Format and Test

on: 
  pull_request:
    branches: main
  push:
    branches: main
concurrency:
# see here for information : https://docs.github.com/en/actions/reference/workflows-and-actions/contexts
  group: ci - ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - uses: actions/setup-python@v7
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
        
      - name : Formatting with black
        uses: psf/black@stable
        with:
          options: "--check --diff"

      - name : Linting with pylint
        run: |
          pylint . --verbose

  
  pytest:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - uses: actions/setup-python@v7
        with:
          python-version: 3.13
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest -v




